### PR TITLE
Replace deprecated truffle-hdwallet-provider to Truffle monorepo's one

### PR DESCRIPTION
**Pull request by Botary**

### CODE REVIEW

**Comment by ylv-io** [comment]
Hey @Botary. Thanks a lot!

**Comment by ylv-io** [comment]
Hey @Botary! Can you pull updates from the master to resolve `package.json` conflicts? Or add me as a collaborator and I'll do it.

**Comment by Botary** [comment]
@ylv-io I've merged the master branch

**Comment by pcowgill** [comment]
@Botary Good catch!

**Comment by ylv-io** [comment]
Hey @Botary! Thanks a lot for your contribution!

**Pull request merged**
