### PR TITLE
Prepare the deprecation of this website

### PR DESCRIPTION
**Pull request by come-maiz**

### CODE REVIEW

**Comment by come-maiz** [comment]
I'm not sure about removing the .netlify directory, please check.
And since we no longer need this website, we can remove the client directory, right?

**Review by ylv-io — CHANGES_REQUESTED** [review]
Hey @elopio! Thanks for taking time to address this!
We do need .netlify dir because it has site id, so it redirect will keep working.
We also need client directory because it has all the code for kit frontend but we can now remove landing page code. I'll address that if you don't mind.

**Comment by come-maiz** [comment]
@ylv-io go for it. Thanks for the info.

**Comment by come-maiz** [comment]
I changed this pr to only add the redirect. The rest is on your side @ylv-io, but let me know if you need a hand next week.

**Comment by ylv-io** [comment]
Hey @elopio! Thanks for helping on this! Much appreciated! 🚀

**Review by ylv-io — COMMENTED** [review]
Perfect.

**Review by ylv-io — COMMENTED** [review]
Perfect.

**Review by ylv-io — COMMENTED** [review]
Perfect

**Pull request merged**
